- id: snakeoil
  name: snakeoil
  description: "Format and lint Python code blocks within markdown"
  entry: snakeoil
  language: python
  types_or: [markdown]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"